"""Execution plans can target local processes, SLURM, or other future adapters."""

from typing import Protocol

from histopilot.domain.jobs import ExecutionPlan, Job


class JobExecutor(Protocol):
    def submit(self, plan: ExecutionPlan) -> Job: ...
    def status(self, job_id: str) -> Job: ...
    def cancel(self, job_id: str) -> None: ...
    def logs(self, job_id: str) -> str: ...
