"""Write the `histopilot` skill's reference from the code, so it cannot drift.

python scripts/skill_reference.py          # write plugins/histopilot/skills/histopilot/reference.md
python scripts/skill_reference.py --check  # exit 1 if it is out of date
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

TARGET = ROOT / "plugins" / "histopilot" / "skills" / "histopilot" / "reference.md"


def _commands() -> list[str]:
    import typer

    from histopilot.cli import app

    rows = []

    def walk(command, prefix):
        for name, sub in sorted(getattr(command, "commands", {}).items()):
            if getattr(sub, "hidden", False):
                continue
            if hasattr(sub, "commands"):
                walk(sub, f"{prefix}{name} ")
                continue
            arguments = " ".join(
                parameter.human_readable_name.upper()
                for parameter in sub.params
                if parameter.param_type_name == "argument"
            )
            summary = (sub.help or "").strip().split("\n")[0]
            rows.append(
                f"| `histopilot {prefix}{name}{' ' + arguments if arguments else ''}` | {summary} |"
            )

    walk(typer.main.get_command(app), "")
    return rows


def render() -> str:
    from histopilot.client.errors import EXIT_CODES, NEXT_STEPS
    from histopilot.client.specs import EXPLICIT, MODELS, SPEC_VERSION
    from histopilot.client.states import RUN_STATES

    lines = [
        "# HistoPilot CLI reference",
        "",
        "Generated by `scripts/skill_reference.py` from the code; do not edit by hand.",
        "The contract behind it is `docs/cli-contract.md`.",
        "",
        "## Commands",
        "",
        "Every command takes `--json`, `--url`, `--project` and `--timeout SECONDS`. Commands "
        "that change records also take `--yes`, `--dry-run`, `--preview-hash HASH` and "
        "`--operation-id ID`; commands that start work take `--wait`; lists take `--limit` and "
        "`--offset`.",
        "",
        "| Command | What it does |",
        "| --- | --- |",
        *_commands(),
        "",
        "## Exit codes",
        "",
        "| Exit | `error.kind` | Next move |",
        "| --- | --- | --- |",
        *(f"| {code} | `{kind}` | {NEXT_STEPS[kind]} |" for kind, code in EXIT_CODES.items()),
        "",
        "## Run states",
        "",
        "Anything that runs carries `runState`: "
        + ", ".join(f"`{state}`" for state in RUN_STATES)
        + ", or `null` before it starts.",
        "",
        "## Spec kinds",
        "",
        f"Spec files start with `kind` and `specVersion: {SPEC_VERSION}`. "
        "`histopilot schema KIND` prints each kind's fields.",
        "",
        "| Kind | Request model | Fields that must be written out |",
        "| --- | --- | --- |",
        *(
            f"| `{kind}` | `{name}` | {', '.join(f'`{field}`' for field in EXPLICIT.get(kind, [])) or '-'} |"
            for kind, (_, name) in MODELS.items()
        ),
        "",
    ]
    return "\n".join(lines)


if __name__ == "__main__":
    from scripts.generated import main

    raise SystemExit(main(__doc__.splitlines()[0], TARGET, render))
