import { Fragment, useRef, useState } from 'react';
import { predictorBuilds, predictorSourceKey, type BuildMethod, type PredictorBuildSelection } from '../api/predictorBuilds';
import { predictorMethodLabel, type PredictorChoice } from '../api/predictors';
import { Badge, ErrorNotice } from './ui';
import { Findings } from './ScientificUI';
import NumericField, { reportEditorValidity } from './NumericField';
import { useBatchReview } from './useBatchReview';
import { cleanupLink } from '../lib/hashRoute';
import './RunWorkspace.css';

export const completedSeedGroup = (item: PredictorChoice) => item.totalRuns > 0 && item.completedRuns === item.totalRuns;
export default function BulkPredictorBuilder({ project, choices, sourceExperiment, refresh }: { project: string; choices: PredictorChoice[]; sourceExperiment: string; refresh: () => Promise<void> }) {
  const [selected, setSelected] = useState<string[]>([]);
  const [search, setSearch] = useState('');
  const [experiment, setExperiment] = useState(sourceExperiment);
  const [groupBy, setGroupBy] = useState<'experiment' | 'none'>('experiment');
  const [method, setMethod] = useState<BuildMethod>('both');
  const [namePrefix, setNamePrefix] = useState('');
  const [percentile, setPercentile] = useState(50);
  const [preset, setPreset] = useState('50');
  const editor = useRef<HTMLFieldSetElement>(null);
  const action = useBatchReview(
    (selection: PredictorBuildSelection) => predictorBuilds.preview(project, selection),
    (selection, preview, operation) => predictorBuilds.create(project, selection, preview.previewHash!, operation),
    (preview) => preview.canBuild, (result) => result.status === 'completed', async () => { await refresh(); },
  );
  const options = choices.filter((choice) => !sourceExperiment || choice.experimentId === sourceExperiment);
  const experiments = [...new Map(options.map((choice) => [choice.experimentId, choice.experimentName])).entries()];
  const visible = options.filter((choice) => (!experiment || choice.experimentId === experiment) && `${choice.experimentName} ${choice.batchName} ${choice.trainingSeed} ${choice.splitSeed}`.toLowerCase().includes(search.trim().toLowerCase())).sort((a, b) => a.experimentName.localeCompare(b.experimentName) || a.batchName.localeCompare(b.batchName) || a.candidateNumber - b.candidateNumber || a.trainingSeed - b.trainingSeed || a.splitSeed - b.splitSeed);
  const chosen = options.filter((item) => selected.includes(predictorSourceKey(item)));
  const groups = groupBy === 'experiment' ? [...new Map(visible.map((item) => [item.experimentId, { label: item.experimentName, items: visible.filter((row) => row.experimentId === item.experimentId) }])).entries()] : [['all', { label: '', items: visible }]] as const;
  function choose(ids: string[]) { action.reset(); setSelected(ids); }
  function review() {
    if (!chosen.length || chosen.length > 128 || chosen.length !== selected.length || !reportEditorValidity(editor.current)) return;
    void action.preview({ selections: chosen.map(({ experimentId, batchId, candidateId, trainingSeed, splitSeed }) => ({ experimentId, batchId, candidateId, trainingSeed, splitSeed })), method, refitPercentile: percentile, ...(namePrefix.trim() ? { namePrefix: namePrefix.trim() } : {}) });
  }
  return <div className="run-workspace">
    <p>Each row is one configuration and seed pair. Select several rows or all completed seeds to build their own predictors.</p>
    <ErrorNotice error={action.error} />
    <fieldset ref={editor} disabled={action.locked} className="chain-fields" onChange={() => action.reset()}>
      <legend className="sr-only">Build predictors settings</legend>
      <div className="run-methods chain-wide" role="group" aria-label="Predictor methods">{(['ensemble', 'refit', 'both'] as const).map((value) => <label key={value} className={method === value ? 'selected' : ''}><input type="radio" name="build-method" value={value} checked={method === value} onChange={() => setMethod(value)} />{value === 'both' ? 'Both' : value === 'refit' ? 'Refit' : 'Ensemble'}</label>)}</div>
      <p className="muted chain-wide">{method === 'ensemble' ? 'Publish an ensemble of existing fold checkpoints for every selected seed.' : method === 'refit' ? 'Create a separate full-development refit plan for every selected seed.' : 'Publish a fold ensemble and create a separate refit plan for every selected seed. Train the refits together from Refit jobs.'}</p>
      <label className="label">Name prefix (optional)<input className="field" maxLength={60} value={namePrefix} onChange={(event) => setNamePrefix(event.target.value)} placeholder="Names include configuration, seed and method" /></label>
      {method !== 'ensemble' ? <><label className="label">Refit epoch percentile<select className="field" value={preset} onChange={(event) => { setPreset(event.target.value); if (event.target.value !== 'custom') setPercentile(Number(event.target.value)); }}><option value="50">Median (P50)</option><option value="75">75th percentile (P75)</option><option value="90">90th percentile (P90)</option><option value="100">Maximum (P100)</option><option value="custom">Custom percentile</option></select></label>{preset === 'custom' ? <NumericField label="Custom percentile" value={percentile} onChange={setPercentile} integer={false} min={1} max={100} /> : null}<p className="muted chain-wide">Each refit uses all development slides. Its epoch budget is the selected percentile of that seed’s best fold epochs, rounded up; test data is excluded.</p></> : null}
    </fieldset>
    <div className="run-toolbar"><label className="label run-search">Search completed runs<input className="field" type="search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Experiment, batch or seed" /></label><label className="label">Experiment<select className="field" disabled={Boolean(sourceExperiment)} value={experiment} onChange={(event) => setExperiment(event.target.value)}><option value="">All experiments</option>{experiments.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label><label className="label">Group by<select className="field" value={groupBy} onChange={(event) => setGroupBy(event.target.value as typeof groupBy)}><option value="experiment">Experiment</option><option value="none">No grouping</option></select></label></div>
    <div className="run-selection-bar"><strong>{chosen.length} seed groups selected · {chosen.length * (method === 'both' ? 2 : 1)} predictor outputs</strong><button type="button" className="text-button" disabled={action.locked} onClick={() => choose([...new Set([...selected, ...visible.filter(completedSeedGroup).map(predictorSourceKey)])])}>Select all completed seeds</button><button type="button" className="text-button" disabled={action.locked || !selected.length} onClick={() => choose([])}>Clear selection</button></div>
    <div className="run-table-scroll"><table className="run-table"><thead><tr><th className="run-check"><span className="sr-only">Select</span></th><th className="run-name">Experiment / batch</th><th className="run-number">Config</th><th className="run-number">Training seed</th><th className="run-number">Split seed</th><th className="run-number">Folds</th><th>Existing outputs</th><th>Readiness</th></tr></thead><tbody>{groups.map(([key, group]) => <Fragment key={key}>{group.label ? <tr className="run-group"><th colSpan={8}>{group.label} · {group.items.length} seed groups</th></tr> : null}{group.items.map((item) => { const key = predictorSourceKey(item); return <tr key={key} className={selected.includes(key) ? 'selected' : ''}><td><input type="checkbox" aria-label={`Select ${item.experimentName} ${item.batchName} configuration ${item.candidateNumber} training seed ${item.trainingSeed} split seed ${item.splitSeed}`} checked={selected.includes(key)} disabled={action.locked || !completedSeedGroup(item)} onChange={(event) => choose(event.target.checked ? [...selected, key] : selected.filter((id) => id !== key))} /></td><td><strong>{item.experimentName}</strong><small>{item.batchName}</small></td><td>{item.candidateNumber}</td><td>{item.trainingSeed}</td><td>{item.splitSeed}</td><td>{item.completedRuns}/{item.totalRuns}</td><td>{Object.keys(item.existingPredictorIds ?? {}).join(' + ') || (item.existingRefitId ? 'Refit planned' : 'None')}</td><td><Badge tone={completedSeedGroup(item) ? 'success' : 'neutral'}>{completedSeedGroup(item) ? 'Ready to review' : 'Incomplete'}</Badge>{item.reason ? <small>{item.reason}</small> : null}</td></tr>; })}</Fragment>)}</tbody></table></div>
    {!visible.length ? <p>No seed groups match this view. Complete a training batch in <a href="#experiments">Experiments</a> to build its predictors.</p> : null}
    <p className="muted">Review up to 128 seed groups at a time. Existing outputs are reused; archived or deleted records must be restored.</p><div className="inline-actions"><button className="btn btn-primary" disabled={action.locked || !chosen.length || chosen.length > 128 || chosen.length !== selected.length} onClick={review}>{action.busy ? 'Checking inputs…' : 'Review predictors'}</button></div>
    {action.review ? <div className="run-bulk-review"><h3>Review predictor builds</h3><Findings findings={action.review.preview.findings} /><p>{action.review.preview.counts.create} new outputs · {action.review.preview.counts.reuse} existing outputs · {action.review.preview.counts.blocked} blocked</p><div className="run-table-scroll"><table className="run-table"><thead><tr><th>Predictor</th><th>Method</th><th>Training / split seed</th><th>Action</th><th>Refit epochs</th><th>Checks</th></tr></thead><tbody>{action.review.preview.items.map((item) => <tr key={item.key}><td>{item.name ?? item.selection.name}</td><td>{predictorMethodLabel(item.selection.method)}</td><td>{item.selection.trainingSeed} / {item.selection.splitSeed}</td><td>{item.action}{item.recordId ? <small><a href={cleanupLink(item.recordId)}>View / restore record</a></small> : null}</td><td>{item.epochBudget?.epochs ?? '—'}</td><td>{item.findings.map((finding) => finding.message).join(' ') || 'Verified'}</td></tr>)}</tbody></table></div>
      {action.review.preview.canBuild ? <><label className="development-check"><input type="checkbox" checked={action.acknowledged} disabled={action.busy || action.submitted} onChange={(event) => action.setAcknowledged(event.target.checked)} />I reviewed the selected seeds, methods and inputs.</label><button className="btn btn-primary" disabled={action.busy || (!action.acknowledged && !action.submitted)} onClick={() => void action.apply()}>{action.busy ? 'Building predictors…' : action.submitted ? 'Retry unfinished builds' : 'Build predictors'}</button></> : null}
    </div> : null}
    {action.result ? <div className="callout" role="status"><strong>{action.result.status === 'completed' ? 'Predictor builds saved.' : 'Some builds need attention. Retry the same request to finish.'}</strong><p>{action.result.items.filter((item) => item.method === 'ensemble' && item.status !== 'failed').length} ensembles available · {action.result.items.filter((item) => item.method === 'refit' && item.status !== 'failed').length} refit outputs available. Open Refit jobs to train and publish them.</p>{action.result.items.filter((item) => item.error).map((item) => <p key={item.key}>{item.selection.name}: {item.error?.message}</p>)}{action.result.status === 'partial' ? <button className="text-button" disabled={action.busy} onClick={action.reset}>Start a new review; keep completed outputs</button> : null}</div> : null}
  </div>;
}
