"""Every error code the local service returns, with its kind.

A kind groups codes by what the caller should do next, and docs/cli-contract.md#exit-codes
maps each kind to a CLI exit code. The CLI imports this module first, so it uses the
standard library only. scripts/error_codes.py scans the raise sites and writes
docs/error-codes.md from them and this table; tests/test_error_codes.py fails when the
three disagree.
"""

KINDS = ("invalid", "refused", "conflict", "not-found", "unavailable", "internal")

ERROR_CODES: dict[str, str] = {
    # invalid: the request is wrong, in a value, a combination or the kind of record it names.
    "ARTIFACT_PATH_INVALID": "invalid",
    "ATTRIBUTE_KEY_REQUIRED": "invalid",
    "CASE_COMPARISON_MISMATCH": "invalid",
    "CASE_COMPARISON_REQUIRED": "invalid",
    "CASE_REVIEW_FILTER_INVALID": "invalid",
    "CLINICAL_FIELD_UNKNOWN": "invalid",
    "CLINICAL_PATIENT_UNAVAILABLE": "invalid",
    "CLINICAL_POSITIVE_CLASS_INVALID": "invalid",
    "COMPARISON_CONTEXT_MISMATCH": "invalid",
    "COMPARISON_PATIENT_MISMATCH": "invalid",
    "DATASET_KIND_INVALID": "invalid",
    "EVALUATION_AGGREGATION_MISMATCH": "invalid",
    "EVALUATION_EXTRACTION_MISMATCH": "invalid",
    "EVALUATION_FEATURE_BUNDLE_AMBIGUOUS": "invalid",
    "EVALUATION_FEATURE_CONTRACT_MISMATCH": "invalid",
    "EVALUATION_PREDICTOR_MISMATCH": "invalid",
    "EVALUATION_THRESHOLD_MISMATCH": "invalid",
    "EXPERIMENT_DATASET_MISMATCH": "invalid",
    "EXPERIMENT_DUPLICATE_BATCH": "invalid",
    "FEATURE_LAYOUT_AMBIGUOUS": "invalid",
    "FEATURE_LAYOUT_NOT_FOUND": "invalid",
    "FOLDER_NAME_INVALID": "invalid",
    "FOLDER_PARENT_INVALID": "invalid",
    "IMPORT_DRAFT_REQUIRED": "invalid",
    "IMPORT_SPEC_INVALID": "invalid",
    "INFERENCE_ATTRIBUTE_INVALID": "invalid",
    "INFERENCE_COMPARISON_INVALID": "invalid",
    "INFERENCE_COMPARISON_MISMATCH": "invalid",
    "INFERENCE_SETTINGS_INCOMPLETE": "invalid",
    "INFERENCE_SLIDE_UNAVAILABLE": "invalid",
    "INTERPRETATION_DUPLICATE_SLIDE": "invalid",
    "INTERPRETATION_ENCODER_MISMATCH": "invalid",
    "INTERPRETATION_INPUT_INVALID": "invalid",
    "INTERPRETATION_LINEAGE_MISMATCH": "invalid",
    "INTERPRETATION_MEMBER_INVALID": "invalid",
    "INTERPRETATION_PACK_MISMATCH": "invalid",
    "INTERPRETATION_PATCH_INVALID": "invalid",
    "INTERPRETATION_SLIDE_UNAVAILABLE": "invalid",
    "INTERPRETATION_VIEW_INVALID": "invalid",
    "INVALID_ARTIFACT": "invalid",
    "INVALID_BATCH": "invalid",
    "INVALID_CACHE": "invalid",
    "INVALID_CHECKPOINT": "invalid",
    "INVALID_CONFIGURATION": "invalid",
    "INVALID_COORDS": "invalid",
    "INVALID_DATASET": "invalid",
    "INVALID_DOCUMENT": "invalid",
    "INVALID_DRAFT_KIND": "invalid",
    "INVALID_EVALUATION_DRAFT": "invalid",
    "INVALID_EVALUATION_SPEC": "invalid",
    "INVALID_EXPERIMENT": "invalid",
    "INVALID_EXPERIMENT_DRAFT": "invalid",
    "INVALID_EXPERIMENT_REFERENCE": "invalid",
    "INVALID_FEATURE_BUNDLE": "invalid",
    "INVALID_FEATURE_SET": "invalid",
    "INVALID_INFERENCE_COHORT": "invalid",
    "INVALID_INPUT": "invalid",
    "INVALID_LIFECYCLE_CHANGE": "invalid",
    "INVALID_OUTPUT": "invalid",
    "INVALID_PARENT": "invalid",
    "INVALID_PATH": "invalid",
    "INVALID_PREDICTOR": "invalid",
    "INVALID_PROTOCOL": "invalid",
    "INVALID_PROTOCOL_DRAFT": "invalid",
    "INVALID_PROTOCOL_SPEC": "invalid",
    "INVALID_RESOURCE_TYPE": "invalid",
    "INVALID_REVIEW_COHORT": "invalid",
    "INVALID_REVIEW_PAGE": "invalid",
    "INVALID_REVISION": "invalid",
    "INVALID_SLIDES": "invalid",
    "INVALID_SLIDE_LIST": "invalid",
    "INVALID_TARGET_SPLIT": "invalid",
    "INVALID_TARGET_SPLIT_DRAFT": "invalid",
    "INVALID_TARGET_SPLIT_SPEC": "invalid",
    "INVALID_TRAINING_RECIPE": "invalid",
    "INVALID_TRAINING_SPLIT": "invalid",
    "INVALID_TRIDENT_OPTIONS": "invalid",
    "INVALID_VERSION_LABEL": "invalid",
    "MAPPING_COLUMN_MISSING": "invalid",
    "MORPHOLOGY_DATASET_MISMATCH": "invalid",
    "MORPHOLOGY_REGION_INVALID": "invalid",
    "PACK_FEATURE_MISMATCH": "invalid",
    "PATH_INVALID": "invalid",
    "PATH_NOT_ABSOLUTE": "invalid",
    "PATH_NOT_DIRECTORY": "invalid",
    "PATIENT_ANALYSIS_DISABLED": "invalid",
    "PERFORMANCE_ATTRIBUTE_INVALID": "invalid",
    "PREDICTOR_CANDIDATE_MISSING": "invalid",
    "PREDICTOR_CHECKPOINT_INVALID": "invalid",
    "PREDICTOR_EXPERIMENT_MISMATCH": "invalid",
    "PROJECT_MIL_MODEL_UNSUPPORTED": "invalid",
    "REFERENCE_CLASSES_MISMATCH": "invalid",
    "REFERENCE_COHORT_INVALID": "invalid",
    "REFERENCE_COHORT_MISMATCH": "invalid",
    "REFIT_METHOD_REQUIRED": "invalid",
    "REFIT_RESOURCES_INVALID": "invalid",
    "REQUEST_INVALID": "invalid",
    "REVIEW_CONTEXT_INVALID": "invalid",
    "SETUP_VERSION_REQUIRED": "invalid",
    "SHEET_INVALID": "invalid",
    "SLIDE_ROOT_REQUIRED": "invalid",
    "SLIDE_VIEW_INVALID": "invalid",
    "TABLE_EMPTY": "invalid",
    "TABLE_ENCODING": "invalid",
    "TABLE_FILE_REQUIRED": "invalid",
    "TABLE_FORMAT_UNSUPPORTED": "invalid",
    "TABLE_HEADERS_DUPLICATE": "invalid",
    "TABLE_HEADERS_INVALID": "invalid",
    "TABLE_INVALID": "invalid",
    "TABLE_ROW_WIDTH": "invalid",
    "TARGET_CONTRACT_MISMATCH": "invalid",
    "TARGET_SPLIT_DATASET_MISMATCH": "invalid",
    "TARGET_SPLIT_TARGET_MISMATCH": "invalid",
    "TARGET_SPLIT_UNIT_MISMATCH": "invalid",
    "TASK_ACTION_INVALID": "invalid",
    "TASK_CENTER_FILTER_INVALID": "invalid",
    "TASK_CENTER_SETTINGS_INVALID": "invalid",
    "TASK_DEPENDENCY_UNKNOWN": "invalid",
    "TASK_INVALID": "invalid",
    "TOKEN_LIFETIME_INVALID": "invalid",
    "TOKEN_SCOPE_INVALID": "invalid",
    "TRAINING_FEATURE_KIND_MISMATCH": "invalid",
    "TRAINING_METRIC_UNAVAILABLE": "invalid",
    "TRAINING_MODEL_UNSUPPORTED": "invalid",
    "TRAINING_OOF_UNIT_INVALID": "invalid",
    "TRAINING_RECIPE_UNAVAILABLE": "invalid",
    "TRAINING_RUNS_REQUIRED": "invalid",
    "UNKNOWN_ATTRIBUTE": "invalid",
    "UPLOAD_INVALID": "invalid",
    # refused: well-formed, but a state, rule, limit or policy forbids it: blocking findings,
    # a frozen, archived or running record, changed evidence, a missing optional component.
    "AGENT_REQUEST_NOT_CLAIMED": "refused",
    "AGENT_REQUEST_SETTLED": "refused",
    "AGREEMENT_UNAVAILABLE": "refused",
    "ARTIFACT_CORRUPT": "refused",
    "ARTIFACT_LIMIT": "refused",
    "BATCH_HAS_FROZEN_PREDICTOR": "refused",
    "BATCH_PREFLIGHT_BLOCKED": "refused",
    "BATCH_TOO_LARGE": "refused",
    "CASE_REVIEW_EVIDENCE_INVALID": "refused",
    "CASE_REVIEW_LIMIT": "refused",
    "CLEANUP_BLOCKED": "refused",
    "CLEANUP_EVIDENCE_INVALID": "refused",
    "CLEANUP_LIMIT": "refused",
    "CLEANUP_PROCESS_UNKNOWN": "refused",
    "CLINICAL_COVERAGE_MISSING": "refused",
    "CLINICAL_EVIDENCE_INVALID": "refused",
    "CLINICAL_FIELDS_MISSING": "refused",
    "CLINICAL_IDENTITY_AMBIGUOUS": "refused",
    "CLINICAL_INPUTS_CHANGED": "refused",
    "CLINICAL_NO_LABELED_OUTCOMES": "refused",
    "CLINICAL_PATIENT_IDENTITIES_UNVERIFIED": "refused",
    "CLINICAL_TARGET_LEAKAGE": "refused",
    "CLINICAL_VALUES_INVALID": "refused",
    "COMPARISON_EVIDENCE_CHANGED": "refused",
    "COMPARISON_EVIDENCE_INVALID": "refused",
    "COMPARISON_REQUIRES_LABELS": "refused",
    "COMPUTE_ACTIVE": "refused",
    "COMPUTE_PLAN_CHANGED": "refused",
    "COMPUTE_RESOURCES_UNAVAILABLE": "refused",
    "COMPUTE_RESULT_CHANGED": "refused",
    "COMPUTE_RESUME_REQUIRED": "refused",
    "COMPUTE_STATE_INVALID": "refused",
    "CONFLICTING_PATIENT_LABELS": "refused",
    "CREATED_BEFORE_TASK_CENTER": "refused",
    "DATASET_SLIDE_FOLDER_UNAVAILABLE": "refused",
    "DEMO_PROJECT_READ_ONLY": "refused",
    "DEMO_STORE_UNAVAILABLE": "refused",
    "DEVELOPMENT_FEATURE_BINDING_MISMATCH": "refused",
    "DEVELOPMENT_FEATURE_COVERAGE": "refused",
    "DEVELOPMENT_MEMBERSHIPS_MISSING": "refused",
    "DEVELOPMENT_PATIENT_OVERLAP": "refused",
    "DEVELOPMENT_SLIDE_OVERLAP": "refused",
    "DEVELOPMENT_SLIDE_SOURCE_OVERLAP": "refused",
    "DIRECTORY_UNREADABLE": "refused",
    "DOCUMENT_TOO_LARGE": "refused",
    "DRAFT_FROZEN": "refused",
    "DUPLICATE_FEATURE_ID": "refused",
    "DUPLICATE_SLIDE_ID": "refused",
    "DUPLICATE_TEST_SLIDE_SOURCE": "refused",
    "EMPTY_TARGET_SPLIT_PARTITION": "refused",
    "EMPTY_TEST_COHORT": "refused",
    "ENCODER_IDENTITY_REQUIRED": "refused",
    "ENCODER_MISMATCH": "refused",
    "EVALUATION_BATCH_BLOCKED": "refused",
    "EVALUATION_BATCH_CHANGED": "refused",
    "EVALUATION_BATCH_LIMIT": "refused",
    "EVALUATION_COVERAGE_CHANGED": "refused",
    "EVALUATION_DEVELOPMENT_OVERLAP": "refused",
    "EVALUATION_ENCODER_UNVERIFIABLE": "refused",
    "EVALUATION_EVIDENCE_CHANGED": "refused",
    "EVALUATION_EVIDENCE_INVALID": "refused",
    "EVALUATION_EXTRACTION_UNVERIFIABLE": "refused",
    "EVALUATION_FEATURE_BUNDLE_REQUIRED": "refused",
    "EVALUATION_INPUTS_CHANGED": "refused",
    "EVALUATION_PACK_CHANGED": "refused",
    "EVALUATION_PREFLIGHT_BLOCKED": "refused",
    "EVALUATION_RECORD_LIMIT": "refused",
    "EVALUATION_RESULT_CHANGED": "refused",
    "EXPERIMENT_ACTIVE": "refused",
    "EXPERIMENT_ALREADY_FROZEN": "refused",
    "EXPERIMENT_ALREADY_SUBMITTED": "refused",
    "EXPERIMENT_ARCHIVED": "refused",
    "EXPERIMENT_BATCHES_REQUIRED": "refused",
    "EXPERIMENT_BATCH_INACTIVE": "refused",
    "EXPERIMENT_BATCH_INPUTS_MISMATCH": "refused",
    "EXPERIMENT_CONFIGURATION_LOCKED": "refused",
    "EXPERIMENT_COPY_INVALID": "refused",
    "EXPERIMENT_FINISHED": "refused",
    "EXPERIMENT_FOLDS_INCOMPLETE": "refused",
    "EXPERIMENT_INPUTS_INVALID": "refused",
    "EXPERIMENT_INPUTS_REQUIRED": "refused",
    "EXPERIMENT_OWNER_CHANGED": "refused",
    "EXPERIMENT_PREDICTORS_LEGACY": "refused",
    "EXPERIMENT_PREDICTORS_LOCKED": "refused",
    "EXPERIMENT_PREDICTOR_PLAN_CHANGED": "refused",
    "EXPERIMENT_PREDICTOR_POLICY_LOCKED": "refused",
    "EXPERIMENT_REFIT_STOPPED": "refused",
    "EXPERIMENT_RUNTIME_CHANGED": "refused",
    "EXPERIMENT_SETUP_CHANGED": "refused",
    "EXPERIMENT_SETUP_FROZEN": "refused",
    "EXPERIMENT_SETUP_INPUTS_REQUIRED": "refused",
    "EXPERIMENT_SETUP_REQUIRED": "refused",
    "EXPERIMENT_SUBMISSION_REQUIRED": "refused",
    "EXPERIMENT_TOO_LARGE": "refused",
    "EXPERIMENT_TYPED_ENDPOINT_REQUIRED": "refused",
    "EXPOSURE_METADATA": "refused",
    "EXPOSURE_NONE": "refused",
    "EXTRACTION_ACTIVE": "refused",
    "EXTRACTION_CORRUPT": "refused",
    "EXTRACTION_INVALID": "refused",
    "EXTRACTION_LIMIT": "refused",
    "FALLBACK_PATIENT_ID_COLLISION": "refused",
    "FEATURES_INVALID": "refused",
    "FEATURE_BUNDLE_INVALID": "refused",
    "FEATURE_DIMENSION_MISMATCH": "refused",
    "FEATURE_DTYPE_MISMATCH": "refused",
    "FEATURE_KIND_MISMATCH": "refused",
    "FEATURE_SCAN_LIMIT": "refused",
    "FEATURE_SOURCE_CHANGED": "refused",
    "FEATURE_VERIFICATION_CHANGED": "refused",
    "FOLDER_CREATE_FAILED": "refused",
    "FOLDER_CREATION_UNSUPPORTED": "refused",
    "FOLDER_EXISTS": "refused",
    "FOLDER_NO_SPACE": "refused",
    "FOLDER_PARENT_SYMLINK": "refused",
    "FOLDER_PERMISSION_DENIED": "refused",
    "IDENTIFIER_TARGET": "refused",
    "IMPORT_BLOCKED": "refused",
    "IMPORT_TOO_LARGE": "refused",
    "INFERENCE_SLIDE_IMAGE_MISSING": "refused",
    "INTERPRETATION_BATCH_LIMIT": "refused",
    "INTERPRETATION_CLINICAL_DATA_REQUIRED": "refused",
    "INTERPRETATION_DATASET_FOLDER_UNAVAILABLE": "refused",
    "INTERPRETATION_ENCODER_MISSING": "refused",
    "INTERPRETATION_FEATURE_MISMATCH": "refused",
    "INTERPRETATION_FOLDER_INVALID": "refused",
    "INTERPRETATION_FOLDER_UNREADABLE": "refused",
    "INTERPRETATION_LEGACY_VIEW_LIMIT": "refused",
    "INTERPRETATION_MEMORY_INSUFFICIENT": "refused",
    "INTERPRETATION_MODEL_UNSUPPORTED": "refused",
    "INTERPRETATION_PATH_INVALID": "refused",
    "INTERPRETATION_PREDICTOR_INVALID": "refused",
    "INTERPRETATION_RECEIPT_INVALID": "refused",
    "INTERPRETATION_RESULT_CHANGED": "refused",
    "INTERPRETATION_SCAN_LIMIT": "refused",
    "INVALID_ATTRIBUTE": "refused",
    "INVALID_FILTER_VALUE": "refused",
    "INVALID_REGEX": "refused",
    "INVALID_SLIDE": "refused",
    "INVALID_SOURCE_EXTRACTION": "refused",
    "LEGACY_DEVELOPMENT_PROTOCOL": "refused",
    "LEGACY_EXPERIMENT_READ_ONLY": "refused",
    "LEGACY_PROTOCOL_SPLIT": "refused",
    "LIFECYCLE_CORRUPT": "refused",
    "LIFECYCLE_LIMIT": "refused",
    "METADATA_LIMIT": "refused",
    "MIL_BAG_PLANNING_INVALID": "refused",
    "MISSING_PATIENT_ID": "refused",
    "MISSING_TARGET_LABEL": "refused",
    "MISSING_TEST_FEATURES": "refused",
    "MISSING_TEST_PACK_SLIDES": "refused",
    "MORPHOLOGY_DATASET_INVALID": "refused",
    "MORPHOLOGY_INDEX_LIMIT": "refused",
    "MORPHOLOGY_INVALID": "refused",
    "MORPHOLOGY_PATCH_FEATURES_REQUIRED": "refused",
    "MORPHOLOGY_SCOPE_REQUIRED": "refused",
    "MORPHOLOGY_SOURCE_CHANGED": "refused",
    "NESTED_SELECTION_REQUIRED": "refused",
    "OPERATION_CONFLICT": "refused",
    "OUTPUT_IMMUTABLE": "refused",
    "PACKING_CORRUPT": "refused",
    "PACKING_INVALID": "refused",
    "PACKING_LIMIT": "refused",
    "PACKING_UNSAFE_LOCK": "refused",
    "PACK_BINDING_CHANGED": "refused",
    "PACK_NOT_CURRENT": "refused",
    "PACK_NOT_IN_BUNDLE": "refused",
    "PACK_SOURCE_CHANGED": "refused",
    "PACK_VERIFICATION_REFRESH_REQUIRED": "refused",
    "PACK_VERIFICATION_REQUIRED": "refused",
    "PATH_OUTSIDE_ROOTS": "refused",
    "PATH_REFUSED": "refused",
    "PATH_UNRESOLVABLE": "refused",
    "PATIENT_AGGREGATION_UNSUPPORTED": "refused",
    "PERFORMANCE_REQUIRES_LABELS": "refused",
    "PORTABILITY_CHECKSUM_MISMATCH": "refused",
    "PORTABILITY_INVALID": "refused",
    "PREDICTOR_BUILD_BLOCKED": "refused",
    "PREDICTOR_BUILD_RECEIPT_INVALID": "refused",
    "PREDICTOR_CHECKPOINT_CHANGED": "refused",
    "PREDICTOR_CLINICAL_PROVENANCE_CHANGED": "refused",
    "PREDICTOR_EVIDENCE_INVALID": "refused",
    "PREDICTOR_FEATURES_INVALID": "refused",
    "PREDICTOR_FEATURE_KIND_MISMATCH": "refused",
    "PREDICTOR_FOLDS_INCOMPLETE": "refused",
    "PREDICTOR_INACTIVE": "refused",
    "PREDICTOR_MODEL_UNSUPPORTED": "refused",
    "PREDICTOR_PROCESS_UNKNOWN": "refused",
    "PREDICTOR_PROVENANCE_CHANGED": "refused",
    "PREDICTOR_RECORD_INACTIVE": "refused",
    "PREDICTOR_REFIT_REQUIRED": "refused",
    "PREDICTOR_SELECTION_CHANGED": "refused",
    "PREDICTOR_VALIDATION_SELECTION_REQUIRED": "refused",
    "PROJECT_ALREADY_REGISTERED": "refused",
    "PROJECT_DESCRIPTOR_INVALID": "refused",
    "PROJECT_DESCRIPTOR_TOO_LARGE": "refused",
    "PROJECT_DESCRIPTOR_UNREADABLE": "refused",
    "PROJECT_DESCRIPTOR_UNSAFE": "refused",
    "PROJECT_EXISTS": "refused",
    "PROJECT_FOLDER_INACCESSIBLE": "refused",
    "PROJECT_FOLDER_NOT_EMPTY": "refused",
    "PROJECT_FOLDER_REASSIGNED": "refused",
    "PROJECT_FOLDER_UNWRITABLE": "refused",
    "PROJECT_ID_MISMATCH": "refused",
    "PROJECT_OUT_OF_SCOPE": "refused",
    "PROJECT_SOURCE_LIMIT": "refused",
    "PROTOCOL_BUNDLE_CHANGED": "refused",
    "PROTOCOL_BUNDLE_MISMATCH": "refused",
    "PROTOCOL_PREFLIGHT_BLOCKED": "refused",
    "PROTOCOL_RECORD_LIMIT": "refused",
    "PUBLICATION_CONFLICT": "refused",
    "RECALIBRATION_REQUIRES_LABELS": "refused",
    "RECALIBRATION_UNAVAILABLE": "refused",
    "RECORD_TRASHED": "refused",
    "REFERENCE_DUPLICATE_SLIDES": "refused",
    "REFERENCE_FIELD_UNKNOWN": "refused",
    "REFERENCE_NO_LABELS": "refused",
    "REFIT_BAG_PLANNING_INVALID": "refused",
    "REFIT_BEST_EPOCH_UNAVAILABLE": "refused",
    "REFIT_CLINICAL_PROVENANCE_CHANGED": "refused",
    "REFIT_EPOCH_INVALID": "refused",
    "REFIT_EVIDENCE_CHANGED": "refused",
    "REFIT_MEMBERSHIP_INVALID": "refused",
    "REFIT_PROVENANCE_CHANGED": "refused",
    "REFIT_TEST_LEAKAGE": "refused",
    "REGEX_TIMEOUT": "refused",
    "REVIEW_DATASET_INVALID": "refused",
    "REVIEW_REQUIRES_SLIDE_TARGET": "refused",
    "REVISION_LIMIT": "refused",
    "RUN_NOT_SCORED": "refused",
    "SCAN_LIMIT": "refused",
    "SCOPE_MISSING": "refused",
    "SEED_ENSEMBLE_SINGLE_GROUP": "refused",
    "SEED_ENSEMBLE_TOO_LARGE": "refused",
    "SESSION_NOT_FOR_TOKENS": "refused",
    "SHARED_PATIENT_NAMESPACE": "refused",
    "SLIDE_FORMAT_UNSUPPORTED": "refused",
    "SLIDE_GEOMETRY_INVALID": "refused",
    "SLIDE_RASTER_TOO_LARGE": "refused",
    "SLIDE_READER_FAILED": "refused",
    "SLIDE_REVIEW_CORRUPT": "refused",
    "SLIDE_REVIEW_LIMIT": "refused",
    "SLIDE_VIEWER_UNAVAILABLE": "refused",
    "SLIDE_VIEW_TOO_LARGE": "refused",
    "SPLIT_UNIT_MISMATCH": "refused",
    "STALE_FEATURE_BUNDLE": "refused",
    "STALE_TEST_PACK": "refused",
    "STORAGE_CORRUPT": "refused",
    "STORAGE_DATABASE_INVALID": "refused",
    "STORAGE_DATABASE_MISSING": "refused",
    "STORAGE_LOCK_FAILED": "refused",
    "STORAGE_READ_FAILED": "refused",
    "STORAGE_SCHEMA_UNSUPPORTED": "refused",
    "STORAGE_SYNC_FAILED": "refused",
    "STORAGE_UNSAFE_PATH": "refused",
    "STORAGE_UNSUPPORTED": "refused",
    "STORAGE_WRITE_FAILED": "refused",
    "TABLE_CELL_LIMIT": "refused",
    "TABLE_COLUMN_LIMIT": "refused",
    "TABLE_ROW_LIMIT": "refused",
    "TABLE_TOO_LARGE": "refused",
    "TARGET_LABEL_MAPPING_MISMATCH": "refused",
    "TARGET_SPLIT_BLOCKED": "refused",
    "TARGET_SPLIT_PATIENT_LEAKAGE": "refused",
    "TARGET_SPLIT_SLIDE_LEAKAGE": "refused",
    "TARGET_SPLIT_SOURCE_CHANGED": "refused",
    "TARGET_TESTING_BLOCKED": "refused",
    "TASK_ACTIVE": "refused",
    "TASK_CENTER_STATE_UNSAFE": "refused",
    "TASK_CENTER_STORE_NEWER": "refused",
    "TASK_CENTER_STORE_UNSUPPORTED": "refused",
    "TASK_OWNER_OTHER_WORKSPACE": "refused",
    "TEST_PACK_UNAVAILABLE": "refused",
    "TOKEN_EXPOSURE_REQUIRED": "refused",
    "TRAINING_ACTIVE": "refused",
    "TRAINING_ALREADY_LAUNCHED": "refused",
    "TRAINING_BATCH_INVALID": "refused",
    "TRAINING_FEATURES_INVALID": "refused",
    "TRAINING_GPU_UNAVAILABLE": "refused",
    "TRAINING_INPUTS_STALE": "refused",
    "TRAINING_LOCATION_CHANGED": "refused",
    "TRAINING_NOT_LAUNCHED": "refused",
    "TRAINING_NOT_RESUMABLE": "refused",
    "TRAINING_OOF_INVALID": "refused",
    "TRAINING_PARTITION_MISSING": "refused",
    "TRAINING_PLAN_CHANGED": "refused",
    "TRAINING_PROCESS_UNKNOWN": "refused",
    "TRAINING_REGISTRY_UNSAFE": "refused",
    "TRAINING_RESOURCES_UNAVAILABLE": "refused",
    "TRAINING_RUNTIME_CHANGED": "refused",
    "TRAINING_RUNTIME_UNAVAILABLE": "refused",
    "TRAINING_RUN_INVALID": "refused",
    "TRAINING_SPLITS_CHANGED": "refused",
    "TRAINING_SPLIT_BLOCKED": "refused",
    "TRAINING_SPLIT_UNSUPPORTED": "refused",
    "TRAINING_STATE_INVALID": "refused",
    "TRAINING_TASK_UNSUPPORTED": "refused",
    "UNKNOWN_FIELD": "refused",
    "UNKNOWN_TARGET_FIELD": "refused",
    "UNMAPPED_TARGET_LABEL": "refused",
    "UPLOAD_TOO_LARGE": "refused",
    "VALIDATION_SELECTION_UNAVAILABLE": "refused",
    "VERSION_LABEL_MISMATCH": "refused",
    "VERSION_TAG_CONFLICT": "refused",
    # conflict: after a wait, a reload or a fresh preview the same request can succeed: a busy
    # project, a stale revision or preview, inputs changed while read, work not yet finished.
    "CLEANUP_PREVIEW_STALE": "conflict",
    "COMPUTE_LAUNCH_UNCERTAIN": "conflict",
    "EVALUATION_COHORT_STALE": "conflict",
    "EVALUATION_NOT_COMPLETED": "conflict",
    "EXPERIMENT_PREDICTORS_LAUNCH_UNCERTAIN": "conflict",
    "EXPOSURE_CONFLICT": "conflict",
    "FEATURE_JOB_BUSY": "conflict",
    "FOLDER_PARENT_CHANGED": "conflict",
    "INTERPRETATION_FOLDER_CHANGED": "conflict",
    "INTERPRETATION_INPUTS_CHANGED": "conflict",
    "INTERPRETATION_NOT_COMPLETED": "conflict",
    "INTERPRETATION_SOURCE_MISMATCH": "conflict",
    "LIFECYCLE_REVISION_CONFLICT": "conflict",
    "MORPHOLOGY_BUSY": "conflict",
    "MORPHOLOGY_INDEX_EXPIRED": "conflict",
    "MORPHOLOGY_SLIDE_CHANGED": "conflict",
    "OUTPUT_BUSY": "conflict",
    "PORTABILITY_ACTIVE_JOBS": "conflict",
    "PREDICTOR_RUN_INCOMPLETE": "conflict",
    "PREVIEW_STALE": "conflict",
    "PROJECT_BUSY": "conflict",
    "PROJECT_CONFIG_CONFLICT": "conflict",
    "PUBLICATION_INTERRUPTED": "conflict",
    "REFIT_INCOMPLETE": "conflict",
    "REVISION_CONFLICT": "conflict",
    "RUN_NOT_COMPLETED": "conflict",
    "SLIDE_READER_BUSY": "conflict",
    "SLIDE_READER_TIMEOUT": "conflict",
    "SLIDE_REVIEW_CONFLICT": "conflict",
    "SLIDE_SOURCE_CHANGED": "conflict",
    "SOURCE_CHANGED": "conflict",
    "SOURCE_RELINK_CONFLICT": "conflict",
    "STALE_PREVIEW": "conflict",
    "TASK_CENTER_CONFLICT": "conflict",
    "TASK_CENTER_UNAVAILABLE": "conflict",
    "TASK_RETRY_BUSY": "conflict",
    "TRAINING_CLEANUP_FAILED": "conflict",
    "TRAINING_OOF_INCOMPLETE": "conflict",
    # not-found: the named record, file or route does not exist.
    "AGENT_REQUEST_NOT_FOUND": "not-found",
    "API_ENDPOINT_UNKNOWN": "not-found",
    "API_METHOD_NOT_ALLOWED": "not-found",
    "ARTIFACT_NOT_FOUND": "not-found",
    "CLINICAL_ANALYSIS_NOT_FOUND": "not-found",
    "CLINICAL_ARTIFACT_NOT_FOUND": "not-found",
    "COMPUTE_NOT_FOUND": "not-found",
    "CONFIGURATION_NOT_FOUND": "not-found",
    "DATASET_NOT_FOUND": "not-found",
    "DIRECTORY_NOT_FOUND": "not-found",
    "DRAFT_NOT_FOUND": "not-found",
    "EVALUATION_ARTIFACT_NOT_FOUND": "not-found",
    "EVALUATION_BATCH_NOT_FOUND": "not-found",
    "EVALUATION_NOT_FOUND": "not-found",
    "EXPERIMENT_NOT_FOUND": "not-found",
    "EXTRACTION_NOT_FOUND": "not-found",
    "FEATURE_BUNDLE_NOT_FOUND": "not-found",
    "FOLDER_PARENT_NOT_FOUND": "not-found",
    "INTERPRETATION_ARTIFACT_NOT_FOUND": "not-found",
    "INTERPRETATION_NOT_FOUND": "not-found",
    "INTERPRETATION_PATCH_NOT_FOUND": "not-found",
    "INTERPRETATION_SLIDE_NOT_FOUND": "not-found",
    "JOB_NOT_FOUND": "not-found",
    "MODEL_EVALUATION_NOT_FOUND": "not-found",
    "PACKING_NOT_FOUND": "not-found",
    "PACK_NOT_FOUND": "not-found",
    "PATH_NOT_FOUND": "not-found",
    "PORTABILITY_NOT_FOUND": "not-found",
    "PREDICTOR_BUILD_NOT_FOUND": "not-found",
    "PREDICTOR_NOT_FOUND": "not-found",
    "PROJECT_DESCRIPTOR_NOT_FOUND": "not-found",
    "PROJECT_NOT_FOUND": "not-found",
    "REFERENCE_NOT_FOUND": "not-found",
    "REFIT_NOT_FOUND": "not-found",
    "REVIEW_SLIDE_NOT_FOUND": "not-found",
    "TASK_LOG_NOT_FOUND": "not-found",
    "TASK_NOT_FOUND": "not-found",
    "TASK_OWNER_NOT_FOUND": "not-found",
    "TOKEN_NOT_FOUND": "not-found",
    "TRAINING_OOF_NOT_FOUND": "not-found",
    "TRAINING_RUN_NOT_FOUND": "not-found",
    # unavailable: the service boundary refused the session over its Host, Origin or token.
    "BROWSER_CONTEXT_REFUSED": "unavailable",
    "CROSS_SITE_REFUSED": "unavailable",
    "HOST_REFUSED": "unavailable",
    "LOGIN_REQUIRED": "unavailable",
    "ORIGIN_REFUSED": "unavailable",
    "ORIGIN_REQUIRED": "unavailable",
    "SESSION_TOKEN_REQUIRED": "unavailable",
    "TOKEN_INVALID": "unavailable",
    # internal: a server fault.
    "COMPUTE_LAUNCH_FAILED": "internal",
    "INTERNAL_ERROR": "internal",
    "TASK_ACTION_FAILED": "internal",
    "TRAINING_LAUNCH_FAILED": "internal",
}

# Codes a scan of the raise sites cannot read, because the raise site takes them from a
# runtime value, listed under the module that raises them. A module with no codes only
# passes on the code of an error that was raised, and registered, elsewhere.
COMPUTED: dict[str, tuple[str, ...]] = {
    # Scores for a run without metrics repeat the stored scoring error's code.
    "histopilot/api/references.py": (),
    # Saving a run whose cohort review has a blocking finding raises that finding's code:
    # the cohort's own checks, filters, identities, and its bundle and pack verification.
    "histopilot/application/evaluation_runs.py": (
        "CONFLICTING_PATIENT_LABELS",
        "DEVELOPMENT_FEATURE_BINDING_MISMATCH",
        "DEVELOPMENT_FEATURE_COVERAGE",
        "DEVELOPMENT_MEMBERSHIPS_MISSING",
        "DEVELOPMENT_PATIENT_OVERLAP",
        "DEVELOPMENT_SLIDE_OVERLAP",
        "DEVELOPMENT_SLIDE_SOURCE_OVERLAP",
        "DUPLICATE_FEATURE_ID",
        "DUPLICATE_SLIDE_ID",
        "DUPLICATE_TEST_SLIDE_SOURCE",
        "EMPTY_TEST_COHORT",
        "ENCODER_IDENTITY_REQUIRED",
        "ENCODER_MISMATCH",
        "FALLBACK_PATIENT_ID_COLLISION",
        "FEATURE_DIMENSION_MISMATCH",
        "FEATURE_DTYPE_MISMATCH",
        "FEATURE_KIND_MISMATCH",
        "FEATURE_SOURCE_CHANGED",
        "FEATURE_VERIFICATION_CHANGED",
        "IDENTIFIER_TARGET",
        "INVALID_FILTER_VALUE",
        "INVALID_REGEX",
        "LEGACY_DEVELOPMENT_PROTOCOL",
        "MISSING_PATIENT_ID",
        "MISSING_TARGET_LABEL",
        "MISSING_TEST_FEATURES",
        "MISSING_TEST_PACK_SLIDES",
        "PACK_BINDING_CHANGED",
        "PACK_NOT_IN_BUNDLE",
        "PACK_VERIFICATION_REQUIRED",
        "PATIENT_AGGREGATION_UNSUPPORTED",
        "PROTOCOL_BUNDLE_CHANGED",
        "PROTOCOL_BUNDLE_MISMATCH",
        "REGEX_TIMEOUT",
        "REVIEW_REQUIRES_SLIDE_TARGET",
        "SHARED_PATIENT_NAMESPACE",
        "SPLIT_UNIT_MISMATCH",
        "STALE_FEATURE_BUNDLE",
        "STALE_TEST_PACK",
        "TARGET_CONTRACT_MISMATCH",
        "TARGET_LABEL_MAPPING_MISMATCH",
        "TEST_PACK_UNAVAILABLE",
        "UNKNOWN_FIELD",
        "UNKNOWN_TARGET_FIELD",
        "UNMAPPED_TARGET_LABEL",
    ),
    # A blocked predictor build raises its first blocking finding; a failed build item
    # repeats its own error.
    "histopilot/application/experiment_predictors.py": ("PREDICTOR_RECORD_INACTIVE",),
    # Opening slides of a dataset without a usable slide folder raises the folder finding.
    "histopilot/application/inference_analysis.py": (
        "DATASET_SLIDE_FOLDER_UNAVAILABLE",
        "INTERPRETATION_DATASET_FOLDER_UNAVAILABLE",
    ),
    # A blocked attention review repeats the preview's error.
    "histopilot/application/interpretation.py": (),
    # Attention sources raise the first bundle, pack or predictor finding, or the folder
    # finding of a dataset without a usable slide folder.
    "histopilot/application/interpretation_gallery.py": (
        "DATASET_SLIDE_FOLDER_UNAVAILABLE",
        "FEATURE_SOURCE_CHANGED",
        "FEATURE_VERIFICATION_CHANGED",
        "INTERPRETATION_DATASET_FOLDER_UNAVAILABLE",
        "INTERPRETATION_ENCODER_MISSING",
        "INTERPRETATION_FEATURE_MISMATCH",
        "INTERPRETATION_MODEL_UNSUPPORTED",
        "PACK_BINDING_CHANGED",
        "PACK_SOURCE_CHANGED",
        "PACK_VERIFICATION_REFRESH_REQUIRED",
        "PACK_VERIFICATION_REQUIRED",
    ),
    # Experiment inputs raise the first protocol-bundle finding, or the training design's
    # issue from development_splits.training_split_issue.
    "histopilot/application/model_experiments.py": (
        "NESTED_SELECTION_REQUIRED",
        "PROTOCOL_BUNDLE_CHANGED",
        "PROTOCOL_BUNDLE_MISMATCH",
        "TRAINING_SPLIT_UNSUPPORTED",
    ),
    # Saving a reference standard with a blocking finding raises that finding's code.
    "histopilot/application/references.py": (
        "REFERENCE_DUPLICATE_SLIDES",
        "REFERENCE_FIELD_UNKNOWN",
        "REFERENCE_NO_LABELS",
    ),
}

# Deprecated names that the service still returns, with the names that replace them.
ALIASES = {"STALE_PREVIEW": "PREVIEW_STALE"}


def kind_for(code: str | None, status: int | None) -> str:
    """A service error's kind: the registry's, else the contract's rule for its status."""
    kind = ERROR_CODES.get(code or "")
    if kind is not None:
        return kind
    code = code or ""
    if status == 401:
        return "unavailable"
    if status in (400, 405, 422):
        return "invalid"
    if status in (403, 413):
        return "refused"
    if status == 404:
        return "not-found"
    if status == 409:
        stale = "STALE" in code or code.endswith("REVISION_CONFLICT")
        return "conflict" if code.endswith("_BUSY") or stale else "refused"
    if status in (408, 429, 503, 504):
        return "conflict"
    if status is None or status >= 500:
        return "internal"
    return "invalid"
